# Generated by Django 5.2.17 on 2026-08-17 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Design & Creative', 'Design & Creative'), ('Performance Marketing', 'Performance Marketing'), ('SEO & Content', 'SEO & Content'), ('Strategy & Operations', 'Strategy & Operations')], default='Engineering', max_length=100)),
                ('location', models.CharField(default='Remote (Global)', max_length=150)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Contract', 'Contract'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance')], default='Full-time', max_length=50)),
                ('experience_level', models.CharField(default='Senior (4+ yrs)', max_length=100)),
                ('salary_range', models.CharField(default='$90,000 — $130,000 / yr', max_length=100)),
                ('overview', models.TextField(help_text='Role summary and impact at Deft Innovations')),
                ('responsibilities', models.JSONField(default=list, help_text='List of key responsibilities')),
                ('requirements', models.JSONField(default=list, help_text='List of skills and qualifications')),
                ('perks', models.JSONField(blank=True, default=list, help_text='List of role perks & benefits')),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to close the job posting')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Position',
                'verbose_name_plural': 'Job Positions',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('portfolio_url', models.URLField(blank=True, max_length=500)),
                ('github_url', models.URLField(blank=True, max_length=500)),
                ('resume_link', models.URLField(help_text='Link to Resume / CV (Google Drive, Dropbox, Notion, etc.)', max_length=500)),
                ('cover_letter', models.TextField(blank=True, help_text='Candidate cover note or intro')),
                ('status', models.CharField(choices=[('New', 'New'), ('In Review', 'In Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Offer Extended', 'Offer Extended'), ('Hired', 'Hired'), ('Rejected', 'Rejected'), ('Archived', 'Archived')], default='New', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for hiring team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='careers.jobposition')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
