# Generated by Django 5.2.17 on 2026-08-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(help_text='Short summary shown on cards and SEO')),
                ('content', models.TextField(help_text='Markdown or rich text article body')),
                ('category', models.CharField(choices=[('Digital Marketing', 'Digital Marketing'), ('Branding', 'Branding'), ('Web Development', 'Web Development'), ('SEO', 'SEO'), ('Social Media', 'Social Media'), ('Business Growth', 'Business Growth'), ('Technology', 'Technology')], default='Technology', max_length=50)),
                ('author_name', models.CharField(default='Marcus Vance', max_length=120)),
                ('author_role', models.CharField(default='Editorial Team', max_length=120)),
                ('author_avatar', models.URLField(blank=True, max_length=500)),
                ('published_at', models.CharField(help_text='e.g. August 10, 2025', max_length=50)),
                ('read_time', models.CharField(default='5 min read', max_length=30)),
                ('image_url', models.URLField(help_text='Cover image URL or hosted asset', max_length=500)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
