# Generated by Django 5.2.17 on 2026-08-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Growth & Marketing', max_length=100)),
                ('icon_name', models.CharField(default='TrendingUp', help_text='Lucide icon name, e.g. TrendingUp, Palette, Code2, Target, Search, Share2', max_length=50)),
                ('deliverables', models.JSONField(default=list, help_text='List of deliverable strings')),
                ('business_benefits', models.JSONField(default=list, help_text='List of benefit strings')),
                ('process_steps', models.JSONField(default=list, help_text='List of process step strings')),
                ('featured_stats', models.JSONField(blank=True, default=dict, help_text="Object: {'label': '...', 'value': '...'}")),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
