# Generated by Django 5.2.17 on 2026-08-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload service image', null=True, upload_to='services/', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional fallback image URL', max_length=500, null=True),
        ),
    ]
