# Generated by Django 5.2.17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_servicecategory_number_servicecategory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, help_text='Paste service image URL', max_length=500, null=True, verbose_name='Cover Image URL'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.URLField(blank=True, help_text='Paste category cover image URL', max_length=500, null=True, verbose_name='Category Image URL'),
        ),
    ]
