# Generated by Django 5.2.17 on 2026-09-16 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_image_alter_servicecategory_image'),
    ]

    operations = [
        # number field was already dropped in 0004 via RunPython SQL
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Optional category description'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon_name',
            field=models.CharField(default='TrendingUp', help_text='Lucide icon name, e.g. TrendingUp, Palette, Code2', max_length=50),
        ),
    ]
