# Generated by Django 5.2.17 on 2026-09-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_servicecategory_number_alter_service_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='number',
        ),
    ]
