# Generated by Django 5.2.17 on 2026-08-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Branding', 'Branding'), ('Web Development', 'Web Development'), ('Digital Marketing', 'Digital Marketing'), ('Performance Marketing', 'Performance Marketing'), ('Social Media', 'Social Media'), ('Creative', 'Creative')], default='Web Development', max_length=50)),
                ('industry', models.CharField(help_text='e.g. Fintech & Private Wealth', max_length=150)),
                ('summary', models.TextField(help_text='Executive summary of the case study')),
                ('challenge', models.TextField(help_text="The client's initial challenges and friction points")),
                ('solution', models.TextField(help_text='Our strategy, execution, and deliverables')),
                ('results', models.JSONField(default=list, help_text="List of objects: [{'metric': '0.35s', 'label': 'Page Load Time'}]")),
                ('services_provided', models.JSONField(default=list, help_text="List of strings: ['Web Development', 'Branding']")),
                ('technologies_used', models.JSONField(default=list, help_text="List of strings: ['Next.js', 'Tailwind']")),
                ('image_url', models.URLField(help_text='Primary hero / cover image', max_length=500)),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of image URLs for project gallery')),
                ('year', models.CharField(default='2025', max_length=20)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Case Study',
                'verbose_name_plural': 'Project Case Studies',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
