# Generated by Django 5.2.17 on 2026-08-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload project image', null=True, upload_to='portfolio/', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video URL (YouTube, Vimeo, etc.)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='Fallback image URL', max_length=500, null=True),
        ),
    ]
