# Generated by Django 5.2.17 on 2026-08-24 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_trustedbrand_industry_trustedbrand_is_featured'),
        ('portfolio', '0002_project_image_project_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_ref',
            field=models.ForeignKey(blank=True, help_text='Link to client brand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='company.trustedbrand'),
        ),
    ]
