# Generated by Django 5.2.17 on 2026-09-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_client_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, help_text='Paste project cover image URL', max_length=500, null=True, verbose_name='Cover Image URL'),
        ),
    ]
