# Generated by Django 5.2.17 on 2026-09-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste a direct MP4 link or Google Drive sharing link. YouTube/Vimeo embed links do NOT work as video sources.', max_length=500, null=True),
        ),
    ]
