# Generated by Django 5.2.17 on 2026-08-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('socials', models.JSONField(blank=True, default=dict, help_text="{'linkedin': '...', 'twitter': '...', 'github': '...'}")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('logo_text', models.CharField(default='CLIENT', max_length=100)),
                ('metric', models.CharField(blank=True, help_text='e.g. +320%', max_length=50)),
                ('metric_label', models.CharField(blank=True, help_text='e.g. Lead Conversion Growth', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'author'],
            },
        ),
        migrations.CreateModel(
            name='TrustStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. 150+', max_length=50)),
                ('label', models.CharField(help_text='e.g. Projects Delivered Globally', max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trust Statistic',
                'verbose_name_plural': 'Trust Statistics',
                'ordering': ['order'],
            },
        ),
    ]
