# Generated by Django 5.2.17 on 2026-08-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Creative Technology & Marketing Agency — Est. 2020', max_length=255)),
                ('headline_primary', models.CharField(default='Building Brands That Move', max_length=255)),
                ('headline_secondary', models.CharField(default='Businesses Forward.', max_length=255)),
                ('subheadline', models.TextField(default='Strategy, creativity, technology & performance marketing — unified into one growth engine for ambitious businesses.')),
                ('primary_cta_text', models.CharField(default='Start a Project', max_length=100)),
                ('primary_cta_link', models.CharField(default='/contact', max_length=255)),
                ('secondary_cta_text', models.CharField(default='View Work', max_length=100)),
                ('secondary_cta_link', models.CharField(default='/portfolio', max_length=255)),
                ('hero_image_url', models.URLField(default='https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=2000&q=90', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section Content',
                'verbose_name_plural': 'Hero Section Content',
            },
        ),
        migrations.CreateModel(
            name='TrustedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand or Client name (e.g. NEXUS GLOBAL CAPITAL)', max_length=150)),
                ('logo_url', models.URLField(blank=True, help_text='Optional logo image URL', max_length=500)),
                ('website_url', models.URLField(blank=True, help_text='Optional brand website URL', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trusted Brand',
                'verbose_name_plural': 'Trusted Brands',
                'ordering': ['order', 'name'],
            },
        ),
    ]
