# Generated by Django 5.2.17 on 2026-08-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_herocontent_trustedbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload team member photo from your system', null=True, upload_to='team/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional fallback image URL', max_length=500, null=True),
        ),
    ]
