# Generated by Django 5.2.17 on 2026-08-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_teammember_photo_alter_teammember_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='socials',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a photo from your computer', null=True, upload_to='team/', verbose_name='Photo'),
        ),
    ]
