# Generated by Django 5.2.17 on 2026-08-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_bio_image_url_socials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herocontent',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Hero Slide', 'verbose_name_plural': 'Hero Slides / Content'},
        ),
        migrations.AlterModelOptions(
            name='trustedbrand',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Trusted Brand / Client', 'verbose_name_plural': 'Trusted Brands / Clients'},
        ),
        migrations.AddField(
            model_name='herocontent',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload custom background image', null=True, upload_to='hero/', verbose_name='Background Image'),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional ambient MP4 background video clip URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trustedbrand',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload brand logo file from your system', null=True, upload_to='brands/', verbose_name='Brand Logo'),
        ),
    ]
