# Generated by Django 5.2.17 on 2026-08-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_herocontent_options_alter_trustedbrand_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herocontent',
            name='hero_image_url',
        ),
        migrations.RemoveField(
            model_name='herocontent',
            name='video_url',
        ),
        migrations.AddField(
            model_name='herocontent',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload an MP4 video for this hero slide', null=True, upload_to='hero/videos/', verbose_name='Hero Video'),
        ),
    ]
