# Generated by Django 5.2.17 on 2026-08-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_video_url_hero_image_url_add_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Photo title / caption (e.g. Global Team Annual Retreat)', max_length=200)),
                ('category', models.CharField(choices=[('Culture & Retreats', 'Culture & Retreats'), ('Creative Lab', 'Creative Lab'), ('Tech & Hackathons', 'Tech & Hackathons'), ('Offsites & Celebrations', 'Offsites & Celebrations'), ('Workspaces', 'Workspaces')], default='Culture & Retreats', help_text='Category / Filter', max_length=100)),
                ('photo', models.ImageField(help_text='Upload high resolution photo', upload_to='gallery/', verbose_name='Photo')),
                ('location', models.CharField(blank=True, default='London Studio', help_text='Location (e.g. Dubai, UAE or London Studio)', max_length=150)),
                ('year', models.CharField(default='2026', help_text='Year (e.g. 2026)', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Culture Gallery Photo',
                'verbose_name_plural': 'Culture Gallery (Life at Deft)',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or specialty description'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='department',
            field=models.CharField(blank=True, default='Engineering & AI', help_text='Department (e.g. Executive Leadership, Engineering & AI, Design & Creative, Growth & Marketing)', max_length=100),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=500),
        ),
    ]
