# Generated by Django 5.2.17 on 2026-08-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_culturegallery_teammember_bio_teammember_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culturegallery',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Gallery Photo', 'verbose_name_plural': 'Gallery (Life at Deft Collage)'},
        ),
        migrations.RemoveField(
            model_name='culturegallery',
            name='category',
        ),
        migrations.RemoveField(
            model_name='culturegallery',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='culturegallery',
            name='location',
        ),
        migrations.RemoveField(
            model_name='culturegallery',
            name='title',
        ),
        migrations.RemoveField(
            model_name='culturegallery',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='culturegallery',
            name='year',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin_url',
        ),
        migrations.AlterField(
            model_name='culturegallery',
            name='photo',
            field=models.ImageField(help_text='Upload gallery image', upload_to='gallery/', verbose_name='Photo'),
        ),
    ]
