# Generated by Django 5.2.17 on 2026-08-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_add_teammember_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturegallery',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
