# Generated by Django 5.2.17 on 2026-08-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_add_culturegallery_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustedbrand',
            name='industry',
            field=models.CharField(blank=True, choices=[('Fintech', 'Fintech'), ('E-Commerce', 'E-Commerce'), ('Healthcare', 'Healthcare'), ('Technology', 'Technology'), ('Real Estate', 'Real Estate'), ('Automotive', 'Automotive'), ('Education', 'Education'), ('Hospitality', 'Hospitality'), ('Retail', 'Retail'), ('Media & Entertainment', 'Media & Entertainment'), ('SaaS', 'SaaS'), ('Non-Profit', 'Non-Profit')], help_text='Client industry for filtering', max_length=100),
        ),
        migrations.AddField(
            model_name='trustedbrand',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Show on landing page clients section'),
        ),
    ]
