# Generated by Django 5.2.17 on 2026-09-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_trustedbrand_industry_trustedbrand_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturegallery',
            name='photo',
            field=models.URLField(blank=True, help_text='Paste gallery image URL', max_length=500, null=True, verbose_name='Photo URL'),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='photo',
            field=models.URLField(blank=True, help_text='Paste background image URL', max_length=500, null=True, verbose_name='Background Image URL'),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='video_file',
            field=models.URLField(blank=True, help_text='Paste video URL (MP4, YouTube, Vimeo)', max_length=500, null=True, verbose_name='Hero Video URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.URLField(blank=True, help_text='Paste team member photo URL', max_length=500, null=True, verbose_name='Photo URL'),
        ),
        migrations.AlterField(
            model_name='trustedbrand',
            name='logo',
            field=models.URLField(blank=True, help_text='Paste brand logo image URL', max_length=500, null=True, verbose_name='Brand Logo URL'),
        ),
    ]
