# Generated by Django 5.2.17 on 2026-09-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_culturegallery_photo_alter_herocontent_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturegallery',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='trustedbrand',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
