# Generated by Django 5.2.17 on 2026-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_add_db_index_to_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image_url',
            field=models.URLField(blank=True, help_text='Profile/cover photo URL (e.g. Unsplash, or an uploaded media path like testimonials/jane.jpg)', max_length=500, verbose_name='Profile Photo URL'),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='video_file',
            field=models.URLField(blank=True, help_text='Paste a direct MP4 link, or a Google Drive sharing link. Do NOT use YouTube/Vimeo embed links.', max_length=500, null=True, verbose_name='Hero Video URL'),
        ),
    ]
