# Generated by Django 5.2.17 on 2026-08-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlead',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='contactlead',
            name='notes',
        ),
        migrations.AlterField(
            model_name='contactlead',
            name='service',
            field=models.CharField(blank=True, help_text='Service the client is interested in', max_length=255),
        ),
    ]
